version: 2
jobs:
  linux:
    docker:
      - image: ubuntu:bionic
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
      - run: apt-add-repository 'deb https://repos.codelite.org/wx3.1.3/ubuntu/ bionic universe'
      - run: apt-get install -y libwxbase3.1-0-unofficial3 libwxbase3.1unofficial3-dev libwxgtk3.1-0-unofficial3 libwxgtk3.1unofficial3-dev wx3.1-headers wx-common
      - run: apt-get update -y
      - run: apt-get install -y libgtk-3-dev pkg-config build-essential git cmake libsqlite3-dev libssh-dev libedit-dev libhunspell-dev clang-format-8 xterm
      - run: mkdir build-release
      - run: cd build-release && cmake .. -DCMAKE_BUILD_TYPE=Release -DMAKE_DEB=1 -DCOPY_WX_LIBS=1
      - run: cd build-release && cmake --build . --target package -j 4
      - run: mkdir deb && mv build-release/*.deb deb
      - store_artifacts: {path: ./deb}

workflows:
  version: 2
  testflow:
    jobs:
      - linux
