site_name: CodeLite Documentation
nav:
    - Download: download.md
    - Build: build_from_sources.md
    - Quick Start: hello_world.md

markdown_extensions:
        - pymdownx.keys
        - admonition

theme: windmill
