site_name: CodeLite Documentation
site_url: https://www.codelite.org
repo_url: https://github.com/eranif/codelite
repo_name: GitHub
edit_uri: edit/master/docs/docs

nav:
    - Download: download.md
    - Build: 
        - wxWidgets: build/build_wx_widgets.md
        - CodeLite: build/build_from_sources.md
        - MinGW: build/mingw_builds.md
    - Quick Start: hello_world.md
    - Settings:
        - Look and feel: settings/colours_and_fonts.md
        - Keyboard shortcuts: settings/keyboard_shortcuts.md
        - Build Settings: settings/build_settings.md
        - Environment Variables: settings/environment_variables.md
    - Workspace:
        - C/C++: workspaces/default.md
        - File System Workspace: workspaces/file_system.md
        - PHP (via plugin): workspaces/php.md
        - Node.js (via plugin): workspaces/nodejs.md
    - Code Completion:
        - C/C++: code_completion/cxx.md
    - Plugins:
        - Language Server Protocol: plugins/lsp.md
        - CMake: plugins/cmake.md
        - SFTP: plugins/sftp.md
        - SnipWiz: plugins/snipwiz.md
        - QMake: plugins/qmake.md
        - CppCheck: plugins/cppcheck.md
        - Subversion: plugins/svn.md
        - wxCrafter: plugins/wxcrafter.md
        - Git: plugins/git.md
        - UnitTest++: plugins/ut.md
    - Debugging:
        - gdb: debuggers/gdb.md
        - lldb: debuggers/lldb.md
        - XDebug (PHP): debuggers/xdebug.md
        - Node.js: debuggers/nodejs.md
        - Quick Debug: debuggers/quick_debug.md
    - wxWidgets:
        - wxWidgets 3.1.5: wxWidgets/repo315.md
    - Misc:
        - Local Preferences: misc/local_preferences.md
        - Sync Project with File System: misc/reconcile_project.md
        - Bookmarks: misc/bookmarks.md
        - Undo & Redo: misc/ur.md
        - Tab Groups: misc/tabgroups.md
        - Tips & Tricks: misc/tips_and_tricks.md

extra_css:
    - stylesheets/extra.css

theme:
    name: material
    palette:
        scheme: default
        primary: black
    highlightjs: true
    font:
        text: Roboto
        code: Roboto Mono

markdown_extensions:
        - pymdownx.keys
        - admonition
        - pymdownx.highlight
        - pymdownx.superfences
        - pymdownx.tasklist:
            custom_checkbox: true
