site_name: CodeLite Documentation
nav:
    - Download: download.md
    - Build: build_from_sources.md
    - Quick Start: hello_world.md
    - Settings:
        - Look and feel: settings/colours_and_fonts.md
        - Keyboard shortcuts: settings/keyboard_shortcuts.md
        - Build Settings: settings/build_settings.md
        
markdown_extensions:
        - pymdownx.keys
        - admonition

theme: windmill
